// <auto-generated />
using System;
using APIBankLoan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIBankloan.Migrations
{
    [DbContext(typeof(BankLoanContext))]
    partial class BankLoanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIBankLoan.Models.BisInfoDetail", b =>
                {
                    b.Property<string>("RefID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cifno")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("businessAddress")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("businessEmail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("businessName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("businessNo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("businessPhoneNo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("contactPerson")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("contactPhoneNo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("initiatorId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("reqBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("roleID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("signature")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("sourceCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("type")
                        .HasColumnType("varchar(255)");

                    b.HasKey("RefID");

                    b.ToTable("bisInfoDetails");
                });

            modelBuilder.Entity("APIBankLoan.Models.authorizers", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("userEmail")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("userId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("userName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("userPhoneNo")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Guid");

                    b.HasIndex("RefID");

                    b.ToTable("Authorizers");
                });

            modelBuilder.Entity("APIBankLoan.Models.authorizers", b =>
                {
                    b.HasOne("APIBankLoan.Models.BisInfoDetail", null)
                        .WithMany("Authorizers")
                        .HasForeignKey("RefID");
                });

            modelBuilder.Entity("APIBankLoan.Models.BisInfoDetail", b =>
                {
                    b.Navigation("Authorizers");
                });
#pragma warning restore 612, 618
        }
    }
}
